version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: throttle-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: throttleDB
      POSTGRES_USER: throttle_user
      POSTGRES_PASSWORD: throttle1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - throttle-network

  redis:
    image: redis:alpine
    container_name: throttle-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - throttle-network

volumes:
  postgres_data:

networks:
  throttle-network:
    driver: bridge
