services:
  postgres:
    image: postgres:16
    container_name: throttle-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: throttleDB
      POSTGRES_USER: throttle_user
      POSTGRES_PASSWORD: throttle1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - throttle-network

  redis:
    image: redis:latest
    container_name: throttle-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - throttle-network

  neo4j:
    image: neo4j:latest
    container_name: throttle-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/throttle1234
    volumes:
      - neo4j_data:/data
    networks:
      - throttle-network

  kafka:
    image: apache/kafka:latest
    container_name: throttle-kafka
    restart: unless-stopped
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - throttle-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: throttle-kafka-ui
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - throttle-network

volumes:
  postgres_data:
  neo4j_data:
  kafka_data:

networks:
  throttle-network:
    driver: bridge
