spring.application.name=throttle

# PostgreSQL DB Config
spring.datasource.url=jdbc:postgresql://localhost:5433/throttleDB
spring.datasource.username=throttle_user
spring.datasource.password=throttle1234

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization (optional)
spring.sql.init.mode=always

# Google Auth
google.client.id=${GOOGLE_CLIENT_ID:570110967969-otsco0oana772nulppb5cslvvks9en9k.apps.googleusercontent.com}
google.auth.require-otp=false

# Email Configuration (for OTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:abhay.kastvar@gmail.com}
spring.mail.password=${MAIL_PASSWORD:wyluaoxzgggjjhym}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
