spring.application.name=throttle

# PostgreSQL DB Config
spring.datasource.url=jdbc:postgresql://localhost:5433/throttleDB
spring.datasource.username=throttle_user
spring.datasource.password=throttle1234

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization (optional)
spring.sql.init.mode=always
