spring.application.name=throttle

# PostgreSQL DB Config
spring.datasource.url=jdbc:postgresql://localhost:5433/throttleDB
spring.datasource.username=throttle_user
spring.datasource.password=throttle1234

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.locations=classpath:db/migration

# SQL Initialization (optional)
spring.sql.init.mode=always

# Google Auth
google.client.id=${GOOGLE_CLIENT_ID:570110967969-otsco0oana772nulppb5cslvvks9en9k.apps.googleusercontent.com}
google.auth.require-otp=false

# Email Configuration (for OTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:abhay.kastvar@gmail.com}
spring.mail.password=${MAIL_PASSWORD:wyluaoxzgggjjhym}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.repositories.enabled=false

# Neo4j Configuration
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=throttle1234

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=throttle-notification-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

# Logging
logging.file.path=logs
logging.file.name=throttle.log
logging.level.com.ridersclub=INFO

# Bike Catalog bootstrap
bike.catalog.external-import.enabled=true
bike.catalog.external-import.timeout-ms=3000
