package com.ridersclub.common.enums;

public enum NotificationType {
    RIDE_CREATED,
    RIDE_JOINED,
    RIDE_INVITE,
    RIDE_STARTED,
    RIDE_COMPLETED,
    GROUP_CREATED,
    SUBGROUP_CREATED,
    SUBGROUP_JOIN_REQUEST,
    SUBGROUP_JOIN_APPROVED,
    SUBGROUP_JOIN_REJECTED,
    ROLE_ASSIGNED,
    ANNOUNCEMENT_PUBLISHED,
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    NEW_FRIEND,
    RIDER_JOINED,
    CLUB_MEMBER_JOINED,
    GENERAL,
    RIDE_REJECTED
}
