name: Spring Boot CI

on:
  push:
    branches:
      - main
      - master
      - throttle_rohan
      - throttle_amit
      - throttle_abhay
      - '**'
  pull_request:
    branches:
      - main
      - master

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        working-directory: ./throttle
        run: mvn clean install
